// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chart struct {
	ID          int64
	SongID      int64
	Charter     string
	Difficulty  string
	SourceID    int64
	DownloadUrl string
	CreatedAt   pgtype.Timestamptz
}

type Song struct {
	ID               int64
	Title            string
	Artist           string
	NormalizedTitle  string
	NormalizedArtist string
	CreatedAt        pgtype.Timestamptz
}

type Source struct {
	ID          int64
	Name        string
	LastScraped pgtype.Timestamptz
}
