// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createChart = `-- name: CreateChart :one
INSERT INTO charts (
    song_id, charter, difficulty, source_id, download_url
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, song_id, charter, difficulty, source_id, download_url, created_at
`

type CreateChartParams struct {
	SongID      int64
	Charter     string
	Difficulty  string
	SourceID    int64
	DownloadUrl string
}

func (q *Queries) CreateChart(ctx context.Context, arg CreateChartParams) (Chart, error) {
	row := q.db.QueryRow(ctx, createChart,
		arg.SongID,
		arg.Charter,
		arg.Difficulty,
		arg.SourceID,
		arg.DownloadUrl,
	)
	var i Chart
	err := row.Scan(
		&i.ID,
		&i.SongID,
		&i.Charter,
		&i.Difficulty,
		&i.SourceID,
		&i.DownloadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
    title, artist, normalized_title, normalized_artist
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (normalized_title, normalized_artist) DO NOTHING
RETURNING id, title, artist, normalized_title, normalized_artist, created_at
`

type CreateSongParams struct {
	Title            string
	Artist           string
	NormalizedTitle  string
	NormalizedArtist string
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Title,
		arg.Artist,
		arg.NormalizedTitle,
		arg.NormalizedArtist,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.NormalizedTitle,
		&i.NormalizedArtist,
		&i.CreatedAt,
	)
	return i, err
}

const getChartsBySongId = `-- name: GetChartsBySongId :many
SELECT id, song_id, charter, difficulty, source_id, download_url, created_at FROM charts
WHERE song_id = $1
ORDER BY difficulty
`

func (q *Queries) GetChartsBySongId(ctx context.Context, songID int64) ([]Chart, error) {
	rows, err := q.db.Query(ctx, getChartsBySongId, songID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chart
	for rows.Next() {
		var i Chart
		if err := rows.Scan(
			&i.ID,
			&i.SongID,
			&i.Charter,
			&i.Difficulty,
			&i.SourceID,
			&i.DownloadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSong = `-- name: GetSong :one
SELECT id, title, artist, normalized_title, normalized_artist, created_at FROM songs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSong(ctx context.Context, id int64) (Song, error) {
	row := q.db.QueryRow(ctx, getSong, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.NormalizedTitle,
		&i.NormalizedArtist,
		&i.CreatedAt,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, artist, normalized_title, normalized_artist, created_at FROM songs
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListSongsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.NormalizedTitle,
			&i.NormalizedArtist,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
